<?php 
	/*
		le code PHP de la page
		déclaration de variables, conditions, etc etc
	*/
?>
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>
			Le site dont vous êtes le héros
		</title>
		<link rel="preconnect" href="https://fonts.googleapis.com/">
		<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="">
		<link href="css2.css" rel="stylesheet">
		<link rel="stylesheet" href="style.css">
	</head>
	<body>
	    <main>
	        <section>
	            
	            
	            
	        </section>
	        
	        
	        
	        
	        
	    </main>
	    
	    
	    
	    
		<!-- le code HTML de la page -->
	</body>
</html>