<?php 
	/*
		le code PHP de la page
		déclaration de variables, conditions, etc etc
	*/
	
	
	
	
	
	
	
?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Le site dont vous êtes le héros
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <body id="home">
        <main>
            <section>
                <h2>Choisissez votre héros préféré ?</h2>
                <div>
                    <form method="get" action="">
                        <div>
                            <select>
                                
                                <option value="Arthur">Arthur</option>
                                <option value="Merlin">Merlin</option>
                                <option value="Lancelot">Lancelot</option>
                             </select>
                            
                        </div>
                        <div>
                            <form action="page2.phtml">
                            <input type="submit" value="Commencer votre aventure" /></form>
                        </div>
                    </form>
                </div>
            </section>
            <section>
                <section>
                    <img src="assets/img/cross-swords.png" />
                    <h1>Le site dont vous êtes le héros</h1>
                </section>
            </section>
        </main>
        <script type="application/javascript" src="assets/js/index.js"></script>
    </body>
</html>